apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"corporate","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"test-svc"}},"template":{"metadata":{"labels":{"run":"test-svc"}},"spec":{"containers":[{"args":["while true; do sleep 30; done;"],"command":["/bin/bash","-c","--"],"image":"openjdk:8-jdk-buster","imagePullPolicy":"Always","name":"corporate","ports":[{"containerPort":8761}]}],"imagePullSecrets":[{"name":"regcred"}]}}}}
    creationTimestamp: "2021-04-24T15:17:02Z"
    generation: 2
    name: corporate
    namespace: default
    resourceVersion: "50229694"
    selfLink: /apis/apps/v1/namespaces/default/deployments/corporate
    uid: e87f00cf-56d5-42a6-81fc-944c2a18e0e1
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: test-svc
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: test-svc
      spec:
        containers:
        - args:
          - while true; do sleep 30; done;
          command:
          - /bin/bash
          - -c
          - --
          image: openjdk:8-jdk-buster
          imagePullPolicy: Always
          name: corporate
          ports:
          - containerPort: 8761
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: regcred
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2021-04-24T15:17:05Z"
      lastUpdateTime: "2021-04-24T15:17:05Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-04-24T15:17:02Z"
      lastUpdateTime: "2021-04-24T15:50:21Z"
      message: ReplicaSet "corporate-b656d965f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"eureka-server","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"test-svc"}},"template":{"metadata":{"labels":{"run":"test-svc"}},"spec":{"containers":[{"args":["while true; do sleep 30; done;"],"command":["/bin/bash","-c","--"],"image":"openjdk:8-jdk-buster","imagePullPolicy":"Always","name":"eureka-server","ports":[{"containerPort":80},{"containerPort":8080},{"containerPort":8761},{"containerPort":11001},{"containerPort":11002},{"containerPort":11004}]}],"imagePullSecrets":[{"name":"regcred"}]}}}}
    creationTimestamp: "2021-04-24T15:15:32Z"
    generation: 1
    name: eureka-server
    namespace: default
    resourceVersion: "50223844"
    selfLink: /apis/apps/v1/namespaces/default/deployments/eureka-server
    uid: 19bc4e50-267f-4cd1-b1e9-1eaaaba2e42e
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: test-svc
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: test-svc
      spec:
        containers:
        - args:
          - while true; do sleep 30; done;
          command:
          - /bin/bash
          - -c
          - --
          image: openjdk:8-jdk-buster
          imagePullPolicy: Always
          name: eureka-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8761
            protocol: TCP
          - containerPort: 11001
            protocol: TCP
          - containerPort: 11002
            protocol: TCP
          - containerPort: 11004
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: regcred
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2021-04-24T15:15:39Z"
      lastUpdateTime: "2021-04-24T15:15:39Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-04-24T15:15:33Z"
      lastUpdateTime: "2021-04-24T15:15:39Z"
      message: ReplicaSet "eureka-server-8869cf796" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"veebsy-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"run":"veebsy-prod"}},"template":{"metadata":{"labels":{"run":"veebsy-prod"}},"spec":{"containers":[{"args":["while true; do sleep 30; done;"],"command":["/bin/bash","-c","--"],"image":"openjdk:8-jdk-buster","imagePullPolicy":"Always","name":"eureka-server","ports":[{"containerPort":80},{"containerPort":8080},{"containerPort":8761}]},{"args":["while true; do sleep 30; done;"],"command":["/bin/bash","-c","--"],"image":"openjdk:8-jdk-buster","imagePullPolicy":"Always","name":"api-gateway"},{"args":["while true; do sleep 30; done;"],"command":["/bin/bash","-c","--"],"image":"openjdk:8-jdk-buster","imagePullPolicy":"Always","name":"corporate"},{"args":["while true; do sleep 30; done;"],"command":["/bin/bash","-c","--"],"image":"openjdk:8-jdk-buster","imagePullPolicy":"Always","name":"corporate-users"},{"args":["while true; do sleep 30; done;"],"command":["/bin/bash","-c","--"],"image":"openjdk:8-jdk-buster","imagePullPolicy":"Always","name":"dictionary-master"}],"imagePullSecrets":[{"name":"regcred"}]}}}}
    creationTimestamp: "2021-03-30T16:16:03Z"
    generation: 1
    name: veebsy-deployment
    namespace: default
    resourceVersion: "44232065"
    selfLink: /apis/apps/v1/namespaces/default/deployments/veebsy-deployment
    uid: 9dbbf829-19d5-4273-9771-419fb50d2eab
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: veebsy-prod
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: veebsy-prod
      spec:
        containers:
        - args:
          - while true; do sleep 30; done;
          command:
          - /bin/bash
          - -c
          - --
          image: openjdk:8-jdk-buster
          imagePullPolicy: Always
          name: eureka-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8761
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
          - while true; do sleep 30; done;
          command:
          - /bin/bash
          - -c
          - --
          image: openjdk:8-jdk-buster
          imagePullPolicy: Always
          name: api-gateway
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
          - while true; do sleep 30; done;
          command:
          - /bin/bash
          - -c
          - --
          image: openjdk:8-jdk-buster
          imagePullPolicy: Always
          name: corporate
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
          - while true; do sleep 30; done;
          command:
          - /bin/bash
          - -c
          - --
          image: openjdk:8-jdk-buster
          imagePullPolicy: Always
          name: corporate-users
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
          - while true; do sleep 30; done;
          command:
          - /bin/bash
          - -c
          - --
          image: openjdk:8-jdk-buster
          imagePullPolicy: Always
          name: dictionary-master
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: regcred
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2021-03-30T16:16:26Z"
      lastUpdateTime: "2021-03-30T16:16:26Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-03-30T16:16:03Z"
      lastUpdateTime: "2021-03-30T16:16:26Z"
      message: ReplicaSet "veebsy-deployment-fb99c8c55" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
